const Deva = {
    duca_Id: 0,
    duca_No_Duca: '',
    duca_No_Correlativo_Referencia: '',
    duca_AduanaRegistro: 0,
    duca_AduanaDestino: 0,
    duca_Regimen_Aduanero: 0,
    duca_Modalidad: '',
    duca_Clase: '',
    duca_FechaVencimiento: new Date().toISOString().split("T")[0],
    duca_Pais_Procedencia: 0,
    duca_Pais_Destino: 0,
    duca_Deposito_Aduanero: '',
    duca_Lugar_Desembarque: 0,
    duca_Manifiesto: '',
    duca_Titulo: '',
    trli_Id: 0,
    duca_Codigo_Declarante: '',
    duca_Numero_Id_Declarante: '',
    duca_NombreSocial_Declarante: '',
    duca_DomicilioFiscal_Declarante: '',
    duca_Codigo_Transportista: '',
    duca_Transportista_Nombre: '',
    motr_Id: 0,
    duca_Conductor_Id: 0,
    duca_ValorTransaccionTotal: 0,
    duca_GastosTransporteTotal: 0,
    duca_GastosSeguroTotal: 0,
    duca_OtrosGastosTotal: 0,
    duca_ValorTotalEnAduana: 0,
    duca_PesoBrutoTotal: 0,
    duca_PesoNetoTotal: 0,
    duca_Finalizado: true,
    usua_UsuarioCreacion: 1,
    duca_FechaCreacion: new Date().toISOString(),
    usua_UsuarioModificacion: 0,
    duca_FechaModificacion: new Date().toISOString(),
    duca_Estado: true,
    emba_Codigo: '',
    tran_IdUnidadTransporte: '',
    tran_TamanioEquipamiento: '',
    deva_FechaAceptacion: new Date().toISOString(),
    decl_NumeroIdentificacion: '',
    tipo_identidad_exportador_descripcion: '',
    nombre_pais_exportador: '',
    decl_Nombre_Raso: '',
    nombre_Aduana_Registro: '' ,
    nombre_Aduana_Destino: '',
    deva_AduanaIngresoId: 0,
    nombre_Aduana_Ingreso: '',
    deva_AduanaDespachoId: 0,
    nombre_Aduana_Despacho: '',
    nombre_pais_importador: '',
    nombre_pais_procedencia: '',
    nombre_pais_exportacion: '',
    nombre_pais_destino: '',
    cont_Id: 0,
    cont_Licencia: '',
    nombre_pais_conductor: '',
    cont_NoIdentificacion: '',
    cont_Nombre: '',
    cont_Apellido: '',
    pais_IdExpedicion: 0,
    tran_Id: 0,
    id_pais_transporte: 0,
    nombre_pais_transporte: '',
    marca_Id: 0,
    transporte_marca_Id: 0,
    transporte_marc_Descripcion: '',
    tran_Chasis: '',
    tran_Remolque: '',
    tran_CantCarga: 0,
    tran_NumDispositivoSeguridad: 0,
    tran_Equipamiento: '',
    tran_TipoCarga: '',
    tran_IdContenedor: '',
    base_Gasto_TransporteM_Importada: 0,
    base_Costos_Seguro: 0,
    baseCalculos_inco_Id: 0,
    baseCalculos_inco_Descripcion: '',
    base_Valor_Aduana: 0,
    deva_ConversionDolares: 0,
    usua_NombreCreacion: '',
    usua_NombreModificacion: '',
    detalles: '',
    impuestos: '',
    valoresTotales: '',
    devas: ''
}

export default Deva