const Empleado = {
empl_Id: 0,
empl_Nombres:'',
empl_Apellidos: '',
empl_DNI: '',
escv_Id: 0,
escv_Nombre: '',
empl_NombreCompleto: '',
empl_Sexo: '',
empl_FechaNacimiento: '',
empl_Telefono: '',
empl_DireccionExacta: '',
pvin_Id: 0,
pvin_Nombre: '',
pais_Id: 0,
pais_Codigo: '',
pais_Nombre: '',
empl_CorreoElectronico: '',
carg_Id: 0,
carg_Nombre: '',
empl_EsAduana: true,
usua_UsuarioCreacion: 0,
usuarioCreacionNombre: '',
empl_FechaCreacion: new Date().toISOString(),
usua_UsuarioModificacion: 0,
usuarioModificacionNombre: '',
empl_FechaModificacion: new Date().toISOString(),
usua_UsuarioEliminacion: 0,
usuarioEliminacionNombre: '',
empl_FechaEliminacion: new Date().toISOString(),
empl_Estado: true,
usua_UsuarioActivacion: 0,
usuarioActivacionNombre: '',
empl_FechaActivacion: new Date().toISOString()
}
export default Empleado