const Declaracion = {
      deva_Id: 0,
      deva_AduanaIngresoId: 0,
      adua_IngresoNombre: "",
      deva_AduanaDespachoId: 0,
      adua_DespachoNombre: "",
      deva_DeclaracionMercancia: "",
      deva_FechaAceptacion: new Date().toISOString(),
      regi_Id: 0,
      regi_Codigo: "",
      regi_Descripcion: "",
      impo_RTN: "",
      impo_Id: 0,
      impo_NumRegistro: "",
      nico_Id: 0,
      nico_Descripcion: "",
      impo_NivelComercial_Otro: "",
      impo_Nombre_Raso: "",
      impo_Direccion_Exacta: "",
      impo_Correo_Electronico: "",
      impo_Telefono: "",
      impo_Fax: "",
      impo_ciudId: 0,
      pvde_Id: 0,
      prov_Nombre_Raso: "",
      prov_Direccion_Exacta: "",
      prov_Correo_Electronico: "",
      prov_Telefono: "",
      prov_Fax: "",
      prov_ciudId: 0,
      coco_Id: 0,
      coco_Descripcion: "",
      pvde_Condicion_Otra: "",
      inte_Id: 0,
      tite_Id: 0,
      inte_Nombre_Raso: "",
      inte_Direccion_Exacta: "",
      inte_Correo_Electronico: "",
      inte_Telefono: "",
      inte_Fax: "",
      inte_ciudId: 0,
      deva_LugarEntrega: "",
      pais_EntregaId: 0,
      inco_Id: 0,
      inco_Descripcion: "",
      inco_Version: "",
      deva_NumeroContrato: "",
      deva_FechaContrato:  new Date().toISOString(),
      foen_Id: 0,
      foen_Descripcion: "",
      deva_FormaEnvioOtra: "",
      deva_PagoEfectuado: false,
      fopa_Id: 0,
      deva_FormaPagoOtra: "",
      emba_Id: 0,
      pais_ExportacionId: 0,
      deva_FechaExportacion: new Date().toISOString(),
      mone_Id: 0,
      mone_Otra: "",
      deva_ConversionDolares: 0,
      deva_Condiciones: "",
      usua_UsuarioCreacion: 0,
      usua_CreacionNombre: "",
      deva_FechaCreacion: new Date().toISOString(),
      usua_UsuarioModificacion: 0,
      usua_ModificacionNombre: "",
      deva_FechaModificacion: new Date().toISOString(),
      deva_Estado: true,
      usua_UsuarioEliminacion: 0,
      deva_FechaEliminacion: new Date().toISOString()
    
  };

  export default Declaracion;