const OrdenCompraModel = {
    orco_Id: 0,
    orco_IdCliente: 0,
    orco_FechaEmision: new Date(),
    orco_FechaLimite: new Date(),
    orco_MetodoPago: 0,
    orco_Materiales: true,
    orco_IdEmbalaje: 0,
    orco_EstadoOrdenCompra: '',
    orco_EstadoFinalizado: '',
    orco_Codigo: '',
    orco_DireccionEntrega: '',
    fopa_Id: 0,
    fopa_Descripcion: '',
    usua_UsuarioCreacion: 0,
    orco_FechaCreacion: new Date(),
    usua_UsuarioModificacion: 0,
    orco_FechaModificacion: new Date(),
    orco_Estado: true,
    clie_Nombre_O_Razon_Social: '',
    clie_Direccion: '',
    clie_RTN: '',
    clie_Nombre_Contacto: '',
    clie_Correo_Electronico: '',
    clie_FAX: '',
    tiem_Id: 0,
    tiem_Descripcion: '',
    usuarioCreacionNombre: '',
    usuarioModificacionNombre: '',

    //Campos para el detalle de la orden de compra
    code_CantidadPrenda: 0,
    code_Id: 0,
    esti_Id: 0,
    esti_Descripcion: '',
    code_FechaProcActual: new Date(),
    proc_Descripcion: '',
    tall_Nombre: '',
    tall_Id: 0,
    code_Sexo: '',
    colr_Id: 0,
    colr_Nombre: '',
    // code_Documento: null,
    // code_Medidas: null,
    proc_IdComienza: 0,
    proc_DescripcionComienza: '',
    proc_IdActual: 0,
    proc_DescripcionActual: '',
    code_Unidad: 0,
    code_Valor: 0,
    code_Impuesto: 0,
    code_Descuento: 0,
    code_EspecificacionEmbalaje: '',
    code_FechaCreacion: new Date(),
    code_FechaModificacion: new Date(),
    code_Estado: true,
    // proc_Actual: null,
    // proc_Comienza: null,
    ordenProduccion: 0,
    faex_Id: 0,
    fechaExportacion: new Date(),
    cantidadExportada: 0,
    fede_Cajas: 0,
    fede_TotalDetalle: 0,
    anio: '',
    fecha:'',
    orco_Conteo: 0,
}

export default OrdenCompraModel;