const PersonaNatural={
    pena_id: 0,
    pers_id: 0,
    pena_DireccionExacta: '',
    Cliente:'',
    ciud_Id: 0,
    pvin_Id: 0,
    pvin_nombre: '',
    escv_Id: 0,
    escv_Nombre: '',
    ofic_Id: 0,
    ofpr_id: 0,
    ofpr_Nombre: '',
    ciud_Nombre: '',
    pena_TelefonoFijo: '',
    pena_TelefonoCelular: '',
    pena_CorreoElectronico: '',
    pena_CorreoAlternativo: '',
    pena_RTN: '',
    pena_ArchivoRTN: '',
    pena_DNI: '',
    pena_ArchivoDNI: '',
    pena_NumeroRecibo: '',
    pena_ArchivoNumeroRecibo: '',
    pena_NombreArchDNI: '',
    usua_UsuarioCreacion: 0,
    pena_FechaCreacion: '',
    usua_UsuarioModificacion: 0,
    pena_FechaModificacion: '',
    pena_estado: true,
    pena_finalizado: false,
    usuarioCreacion:'',
    usuarioModificacion:'',
    peju_CiudadRepresantanteNombre:'',
    peju_ColoniaRepresantanteNombre: '',
    peju_AldeaRepresantanteNombre: '',
    pers_Nombre:'',
    colo_Nombre:'',
    alde_Nombre:'',

};
export default PersonaNatural;
