const PersonaNatural = {
    pena_id: 0,
    pers_id: 0,
    pena_DireccionExacta: '',
    ciud_Id: 0,
    pena_TelefonoFijo: '',
    pena_TelefonoCelular: '',
    pena_CorreoElectronico: '',
    pena_CorreoAlternativo: '',
    pena_RTN: '',
    ArchivoRTN: null,
    ArchivoDNI: null, 
    ArchivoNumeroRecibo: null,
    pena_DNI: '',
    pena_ArchivoDNI: null,
    pena_NumeroRecibo: '',
    pena_ArchivoNumeroRecibo: null,
    pena_NombreArchRTN: '',
    pena_NombreArchRecibo: '',
    pena_NombreArchDNI: '',
    usua_UsuarioCreacion: 0,
    pena_FechaCreacion: '',
    usua_UsuarioModificacion: 0,
    pena_FechaModificacion: '',
    pena_estado: true,
    pena_finalizado: false,
    usuarioCreacion: '',
    usuarioModificacion: '',
    peju_CiudadRepresantanteNombre: '',
    peju_ColoniaRepresantanteNombre: '',
    peju_AldeaRepresantanteNombre: '',
    pers_Nombre: '',
    colo_Nombre: '',
    alde_Nombre: '',
};

export default PersonaNatural;