const PersonaJuridicaModel = {
  peju_Id: 0,
  pers_Id: 0,
  pers_Nombre: '',
  pers_RTN: '',
  escv_Id: 0,
  escv_Nombre: '',
  ofic_Id: 0,
  ofic_Nombre: '',
  ofpr_Id: 0,
  ofpr_Nombre: '',
  ciud_Id: 0,
  ciud_Nombre: '',
  colo_Id: 0,
  colo_Nombre: '',
  alde_Id: 0,
  alde_Nombre: '',
  peju_PuntoReferencia: '',
  peju_NumeroLocalApart: '',
  peju_CiudadIdRepresentante: 0,
  peju_CiudadNombreRepresentante: '',
  peju_ColoniaRepresentante: 0,
  peju_ColoniaNombreRepresentante: '',
  peju_AldeaIdRepresentante: 0,
  peju_AldeaNombreRepresentante: '',
  peju_NumeroLocalRepresentante: '',
  peju_PuntoReferenciaRepresentante: '',
  peju_TelefonoEmpresa: '',
  peju_TelefonoFijoRepresentanteLegal: '',
  peju_TelefonoRepresentanteLegal: '',
  peju_CorreoElectronico: '',
  peju_CorreoElectronicoAlternativo: '',
  usua_UsuarioCreacion: 0,
  usua_UsuarioCreacionNombre: '',
  peju_FechaCreacion: '',
  usua_UsuarioModificacion: 0,
  usua_UsuarioModificacionNombre: '',
  peju_FechaModificacion: '',
};

export default PersonaJuridicaModel;