const PlanificacionPoModel = {
        maqu_Id: 0,
        diasActiva: 0,
        diasInactiva: 0,
        diasTotalesInactiva: 0,
        mahi_Observaciones: '',
        maqu_NumeroSerie: '',
        marq_Nombre: '',
        fecha_inicio: new Date().toISOString(),
        fecha_fin: new Date().toISOString(),
        modu_Nombre: '',
        totalProduccion: 0,
        promedioCantidad: 0,
        promedioDanio: 0,
        promedioProduccion: 0,
        orco_Id: 3,
        clie_Id: 0,
        pedidosTerminados: 0,
        pedidosCurso: 0,
        pedidosPendientes: 0,
        cantidadCompletada: 0,
        procentajeCompletado: 0,
        code_CantidadPrenda: 0,
        code_Sexo: '',
        clie_Nombre_O_Razon_Social: '',
        clie_RTN: '',
        clie_Nombre_Contacto: '',
        clie_Numero_Contacto: '',
        clie_Correo_Electronico: '',
        detalles: '',
        asor_Id: 0,
        asor_OrdenDetId: 0,
        esti_Descripcion: '',
        colr_Nombre: '',
        tall_Nombre: '',
        asor_FechaInicio: new Date().toISOString(),
        asor_FechaLimite: new Date().toISOString(),
        asor_Cantidad: 0,
        proc_Descripcion: '',
        empl_NombreCompleto: '',
        mate_FechaInicio: new Date().toISOString(),
        mate_FechaLimite: new Date().toISOString(),
        mate_Descripcion: '',
        totalCantidad: 0,
        porcentajeProductos: 0,
        precioPromedioMaterial: 0,
        totalMaterial: 0,
        promedioMaterial: 0,
        porcentajeMaterial: 0
}

    export default PlanificacionPoModel;