// Modelo para solicitudes a la API de Prendas Pedidas
const PrendasPedidasModel = {
  orco_Id: 0,
  orco_FechaEmision: "",
  orco_FechaLimite: "",
  orco_Avance: "",
  clie_Id: 0,
  clie_Nombre_O_Razon_Social: "",
  clie_Direccion: "",
  clie_RTN: "",
  clie_Nombre_Contacto: "",
  clie_Numero_Contacto: "",
  clie_Correo_Electronico: "",
  clie_FAX: "",
  orco_Conteo: 0,
  orco_FechaCreacion: "",
  anio: "",
  mes: "",
  mesLabel: "",
  fecha: "",
  fechaAntigua: "",
  fechaReciente: "",
  numeroMes: 0,
  numeroSemana: 0,
  numeroDia: 0,
  totalIngresos: 0,
  esti_Id: 0, // Este es el parámetro importante para la consulta
  prendasSumatoria: 0,
  code_Sexo: "",
  esti_Descripcion: "",
  modu_Nombre: "",
  totalProduccionDia: 0,
  porcentajeProduccion: "",
  cantidadIngresos: 0,
  pais_Nombre: "",
  duca_Pais_Emision_Exportador: 0,
  porcentaje: "",
  merc_Descripcion: "",
  cantidad: 0,
  adua_Nombre: ""
};

export default PrendasPedidasModel;
