const Usuarios = {
    usua_Id: 0,
    usua_Nombre: '',
    usua_Contrasenia: '',
    empl_CorreoElectronico: '',
    emplNombreCompleto: '',
    role_Descripcion: '',
    empl_EsAduana: '',
    usua_esAduana: '',
    empl_Id: 0,
    usua_Image: '',
    usua_URLInicial: '',
    role_Id: 0,
    usua_EsAdmin: false,
    usua_UsuarioCreacion: 0,
    usuarioCreacionNombre: '',
    usua_FechaCreacion: '',
    usua_UsuarioModificacion: 0,
    usuarioModificacionNombre: '',
    usua_FechaModificacion: '',
    usua_UsuarioEliminacion: 0,
    usuarioEliminacionNombre: '',
    usua_FechaEliminacion: '',
    usua_Estado: true,
    usua_UsuarioActivacion: 0,
    usuarioActivacionNombre: '',
    usua_FechaActivacion: null,
};

export default Usuarios;